runtime: custom
vm: true
api_version: 1

manual_scaling:
  instances: 1

handlers:

- url: /manifest.json
  static_files: src/manifest.json
  upload: src/manifest.json
  secure: always

- url: /sw.js
  static_files: src/sw.js
  upload: src/sw.js
  secure: always

- url: /(js|imgs|css|ico)(/.*)
  static_files: src/\1\2
  upload: src/(js|imgs|css|ico)(/.*)
  secure: always

- url: /.*
  script: app.js
  secure: always
