version: 1
runtime: custom
vm: true
api_version: 1

manual_scaling:
  instances: 1

handlers:

- url: /(.*\.(css|js|json|ico|png|map))
  static_files: src/\1
  upload: src/(.*\.(css|js|json|ico|png|map))

#- url: /
#  static_files: static/index.html
#  upload: static/index.html

- url: /.*
  script: app.js
